---

# Tasks about configuration checks
- name: 'CONFIG | Check listen(_ipv6) keys because they are mutually exclusive'
  fail:
    msg: 'Listen and listen_ipv6 are mutually exclusive'
  when:
    - "vsftpd_main_config.boolean_options.listen"
    - "vsftpd_main_config.boolean_options.listen_ipv6"
