---

# Handlers main file for vsftpd role

- name: 'HANDLER | Restart vsftpd'
  become: True
  service:
    name: "{{ vsftpd_service_name }}"
    state: 'restarted'
  when: "vsftpd_service_state != 'stopped'"
  tags:
    - 'role::vsftpd'
    - 'role::vsftpd::config'
    - 'role::vsftpd::install'
