---

dependency:
  name: 'galaxy'
driver:
  name: 'docker'
lint:
  name: 'yamllint'
platforms:
  - name: 'vsftpd-docker-jessie'
    image: 'debian'
    image_version: 'jessie'
  - name: 'vsftpd-docker-trusty'
    image: 'ubuntu'
    image_version: 'trusty'
  - name: 'vsftpd-docker-xenial'
    image: 'ubuntu'
    image_version: 'xenial'
provisioner:
  name: 'ansible'
  lint:
    name: 'ansible-lint'
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: '/usr/bin/env python2.7'
        __vsftpd_main_config:
          boolean_options:
            listen: YES
            listen_ipv6: NO
          string_options:
            listen_address: '127.0.0.1'
        vsftpd_main_config: "{{ _vsftpd_main_config | combine(__vsftpd_main_config, recursive=True) }}"
scenario:
  name: 'default'
verifier:
  name: 'testinfra'
  additional_files_or_dirs:
    - '../../tests'
  lint:
    name: 'flake8'
  options:
    sudo: True
