---

# Role tests

- hosts: 'vsftpd-vagrant-xenial64:vsftpd-docker-xenial'
  name: 'Install tests prerequisites'
  gather_facts: False
  tasks:
    - name: 'PREREQUISITES | APT | Do an apt-get update'
      become: True
      raw: 'apt-get update -qq'
      changed_when: False
    - name: 'PREREQUISITES | APT | Install python 2.7'
      become: True
      raw: 'apt-get install -qq python2.7'
      changed_when: False


- hosts: 'all'
  pre_tasks:
    - name: 'PREREQUISITES | APT | Install net-tools, procps test dependencies'
      become: True
      raw: 'apt-get install -qq net-tools procps'
      changed_when: False
  roles:
    - role: "{{ role_name }}"
  vars:
    role_name: "{{ playbook_dir | dirname | dirname | basename }}"
